const initClientObj = {
    id: null,
    tin: '',
    email: '',
    zip_code: '',
    district: '',
    barangay: '',
    rdo_code: '',
    last_name: '',
    trade_name: '',
    first_name: '',
    middle_name: '',
    branch_code: '',
    description: '',
    month_end: '12',
    phone_number: '',
    first_address: '',
    second_address: '',
    period: 'CALENDAR',
    business_nature: '',
    registered_name: '',
    accounting_period: '',
    classification: 'INDIVIDUAL',
    representative_email: '',
    representative_phone: '',
    representative_first_name: '',
    representative_last_name: '',
    representative_middle_name: '',
}
const initClient = {
    clientArr: [],
    clientErr: {
        tin: '',
        email: '',
        phone: '',
        fiscal: '',
        last_name: '',
        first_name: '',
        middle_name: '',
        branch_code: '',
        first_address: '',
        second_address: '',
        classification: '',
        registered_name: '',
        company_description: '',
        representative_email: '',
        representative_phone: '',
        representative_first_name: '',
        representative_last_name: '',
        representative_middle_name: '',
    },
    totalClients: 0,
    clientObj: initClientObj,
}

export {
    initClient
};